/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. 

By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/
package projectEuler;

public class problem2 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		fibonacciSeries(400);

	}
	
	static void fibonacciSeries(double num) {
		double num1= 0; 
		double num2= 1;
		double result;
		double sum=0;
		
		
		//System.out.print(num1 +" "+ num2);
		
		for(int i=2;i<=num;i++) {
			//System.out.println("sum is " + sum);
			result = num1+num2;
			
			//System.out.print(" "+result);
			
			
			if(result%2==0) {
				sum=sum+result;
			}
			
			num1=num2;
			num2=result;
		}
		System.out.println("sum is " + sum);
	}

}
